apiVersion: apps/v1
kind: Deployment
metadata:
  name: yogi
  labels:
    app: yogi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yogi
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: yogi
    spec:
      volumes:
        - name: yogi-secrets
          secret:
            secretName: yogi-secrets
{{ if .Values.run }}
        - name: yogi-run
          hostPath:
            path: '{{ .Values.run }}'
{{ else }}
        - name: yogi-run
          emptyDir: {}
{{ end }}
{{ if .Values.lib }}
        - name: yogi-lib
          hostPath:
            path: '{{ .Values.lib }}'
{{ else }}
        - name: yogi-lib
          emptyDir: {}
{{ end }}
      containers:
      - name: main
        image: {{ .Values.repositoryTag }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        env:
          - name: OPTS
            value: "-Dyogi.library={{ .Values.library }} -Dyogi.libraryToken=file:/usr/local/yogi/secrets/libraryToken -Dyogi.user=/usr/local/yogi/secrets/userProperties -Dyogi.lib=/usr/local/yogi/lib -Dserver.tomcat.basedir=/usr/local/yogi/run -Dserver.tomcat.accesslog.enabled=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=8000"
        volumeMounts:
          - mountPath: "/usr/local/yogi/lib"
            name: yogi-lib
          - mountPath: "/usr/local/yogi/run"
            name: yogi-run
          - mountPath: "/usr/local/yogi/secrets"
            name: yogi-secrets
            readOnly: true
