apiVersion: v1
kind: Pod
metadata:
  name: yogi
  labels:
    app: yogi
spec:
  volumes:
    - name: yogi-etc
      hostPath:
        path: '/data/etc'
  containers:
  - image: yogi:latest
    name: main
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: "/usr/local/yogi/etc"
        name: yogi-etc
