apiVersion: v1
kind: Pod
metadata:
  name: yogi
  labels:
    app: yogi
spec:
  volumes:
    - name: yogi-etc
      hostPath:
        path: '/storage/yogi/etc'
    - name: yogi-lib
      hostPath:
        path: '/storage/yogi/lib'
    - name: yogi-run
      hostPath:
        path: '/storage/yogi/run'
  containers:
  - image: yogi:latest
    name: main
    imagePullPolicy: IfNotPresent
    env:
      - name: OPTS
        value: "-Dserver.tomcat.basedir=. -Dserver.tomcat.accesslog.enabled=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=8000"
    volumeMounts:
      - mountPath: "/usr/local/yogi/etc"
        name: yogi-etc
      - mountPath: "/usr/local/yogi/lib"
        name: yogi-lib
      - mountPath: "/usr/local/yogi/run"
        name: yogi-run
