#!/bin/sh
# see https://github.com/kubernetes/git-sync/blob/release-3.x/docs/ssh.md

set -e
dest=target/ssh
secret=git-creds
mkdir -p $dest
ssh-keyscan mops.schmizzolin.de > $dest/known_hosts
cp $HOME/.ssh/id_rsa $dest/
ssh-keygen -p -f $dest/id_rsa
kubectl create secret generic $secret --from-file=ssh=$dest/id_rsa --from-file=known_hosts=$dest/known_hosts
rm -rf $dest
