#!/bin/sh
if [ "$#" -ne 1 ] ; then
  echo "installs cert-manager and a letencrypt issuer into the current kubernetes context"
  echo "usage: issuer-setup <email>"
  exit 1
fi
set -e
email=$1
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml

file=file.txt
cat >$file <<PART1
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
PART1
echo "    email: $email" >>$file
cat >>$file <<PART2
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
PART2
kubectl apply -f $file
rm $file
