#!/bin/sh
# I want to connect local docker to a remote docker host
# Easiest would be DOCKER_HOST with ssh url, but that's not supported by fabric8 docker plugin.
# Alternative would be a public docker daemon with authentication, but that's tedious to setup:
# * genereate certs for the respective domain
#   (see https://docs.docker.com/engine/security/protect-access/, remove passphrase with openssl rsa -in ca-key.pem -out new.key,
#    copy to ~/.minikube/files/etc/docker/certs)
# So this script if the best alternative I found -- setup ssh tunnel
if [ "$#" -ne 1 ] ; then
  echo "invalid arguments"
  echo "creates configuration in ./.config to connect to remote docker and kubernetes"
  echo "usage: remote-config <host>"
  exit 1
fi
set -e
host=$1
dir=$(pwd)/.config
mkdir $dir
cd $dir

# docker config

scp "$host:~/.minikube/certs/*" . >$dir/scp.log
envfile=$dir/docker-env
echo "export DOCKER_TLS=1" > $envfile
echo "export DOCKER_HOST=tcp://$host:2376" >> $envfile
echo "export DOCKER_CERT_PATH=$dir" >> $envfile

# kubernetes config

dest=$dir/kube-config
scp "$host:~/.kube/config" $dest
sed "s/\(.*\)server:\(.*\)/\1server: https:\/\/$host:8443/g" $dest >$dest-tmp
mv $dest-tmp $dest
chmod 600 $dest

# success

echo "done"
echo " to point docker to $host: source $envfile"
echo " to point kubernetes to $host: cp $dest"
