apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yogi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
{{ if .Values.tls }}
    cert-manager.io/cluster-issuer: letsencrypt
{{ end }}
spec:
{{ if .Values.tls }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.tls }}
{{ end }}
  rules:
{{ if .Values.host }}
    - host: {{ .Values.host }}
      http:
{{ else }}
    - http:
{{ end }}
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: yogi
                port:
                  number: 80
