#!/bin/sh
# Packages mit private key without passphase into a kubernetes secret
# see https://github.com/kubernetes/git-sync/blob/release-3.x/docs/ssh.md

set -
dest=target/ssh
mkdir -p $dest
ssh-keyscan -4 github.com > $dest/known_hosts || (echo "ssh-keyscan failed"; exit 1)
# etckey was generated with   "ssh-keygen -t rsa"
kubectl create secret generic git-creds --from-file=ssh=etckey/id_rsa --from-file=known_hosts=$dest/known_hosts
rm -rf $dest
echo done

